# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-node-browsers
        ports: 9988:9988

      - image: minio/minio:RELEASE.2018-11-06T01-01-02Z
        command: server /data
        environment:
          MINIO_ACCESS_KEY: ONLY_ON_CIRCLE
          MINIO_SECRET_KEY: CAN_WE_DO_THIS
        ports: 9000:9000

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt"}}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install wheel
            # Package up the package
            python setup.py sdist bdist_wheel

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: integration tests
          command: |
            python3 -m venv venv2
            . venv2/bin/activate
            python3 -m pip install -U --force-reinstall dist/bookstore*.whl

            which jupyter

            /home/circleci/repo/venv2/bin/python --version

            npm i
            node ci/integration.js
